#!/bin/bash
## Requierement: Git, Eclipse based IDE(StmCubeIde, Mcuxpressoide, etc.
## Automatically generate a file with git branch and revision info
##
##	 Insert "${ProjDirPath}/git-create-revisioninfo-hook.sh ${ProjDirPath}" to
##	 project properties > C/C++ Build > Settings > Build Steps > pre-build setps > command
##	 	
##    for Linux systems: chmod +x .git/hooks/post-*
##    for Windows systems: create script file with following content

FILENAME="$1/Core/Inc/version.h"

exec 1>&2
branch=`git rev-parse --abbrev-ref HEAD`
shorthash=`git log --pretty=format:'0x%h' -n 1`
revcount=`git log --oneline | wc -l`
latesttag=`git describe --tags --abbrev=0 --always`
message=`git log --format=%B -n 1 $GIT_LATEST_TAG`
stamp=`git log --date=format:'%Y-%m-%d %H:%M:%S' --format=%ad -n 1 $GIT_LATEST_TAG`


echo "// Automatically generated by GIT hook. Do not edit manually." > $FILENAME
echo "" >> $FILENAME
echo "#define GIT_BRANCH \"$branch\"" >> $FILENAME
echo "#define GIT_LATEST_TAG $latesttag" >> $FILENAME
echo "#define GIT_REVCOUNT $revcount" >> $FILENAME
echo "#define GIT_SHORT_HASH $shorthash" >> $FILENAME
echo "#define GIT_COMMIT_MESSAGE \"$message\"" >> $FILENAME
echo "#define GIT_COMMIT_STAMP \"$stamp\"" >> $FILENAME
