// Automatically generated by GIT hook. Do not edit manually.

#define GIT_BRANCH "lpc_init"
#define GIT_LATEST_TAG 7a70e417be61d97f3d7bb207c87e2717a0efdae4
#define GIT_REVCOUNT 58
#define GIT_SHORT_HASH 0x7a70e41
#define GIT_COMMIT_MESSAGE "Set MUX program to all LPC on change it via modbus."
#define GIT_COMMIT_STAMP "2024-02-29 15:03:10"
