// Automatically generated by git hook. Do not edit manually.

#define GIT_BRANCH "sync"
#define GIT_LATEST_TAG cf00d2142900304e8f14e1e3c8d2303fc41ec219
#define GIT_REVCOUNT 41
#define GIT_SHORT_HASH 0xcf00d21
#define GIT_COMMIT_MESSAGE "USB state start from CDC_STATE = CDC_BUSY."
#define GIT_COMMIT_STAMP "2024-01-19 17:20:26"
